import type { Metadata } from "next";
import "../globals.css";
import { MobileMenu } from "@/components/MenuMobile";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function PrivateLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <>
 
        <MobileMenu />
        <div className="min-h-screen mb-15 mt-20  p-2">{children}</div>
  
    </>
  );
}
