import type { Metadata } from "next";
import "../globals.css";
import { MobileMenu } from "@/components/MenuMobile";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-screen mb-15 mt-20 flex items-center justify-center p-2">
      <MobileMenu />
      {children}
    </div>
  );
}
