import type { Metadata } from "next";
import "../globals.css";
import { MobileMenu } from "@/components/MenuMobile";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="">
      <MobileMenu />
      {children}
    </div>
  );
}
